### ISSUE TITLE
No entity manager defined for class with Doctrine Decorator : Issue and Fix proposal ;-)

### ISSUE THREAD

**Issue by michkinn** [sonata-project/SonataDoctrineORMAdminBundle#1405]
In our project, we use a class to decorate the default doctrine.orm.default_entity_manager.

```
services:
  doctrine.orm.entity_manager:
    class: App\Core\Doctrine\ORM\EntityManager
    autowire: true
    decorates: 'doctrine.orm.default_entity_manager'
```

in this case the method getEntityManager in FieldDescriptionFactory throw an exception because $this->registry->getManagerForClass($class); returns an instance of my class (App\Core\Doctrine\ORM\EntityManager).

it is easily fixable by replacing the "getEntityManager" function in FieldDescriptionFactory by the following

```
private function getEntityManager(string $class): EntityManagerInterface
    {
        $em = $this->registry->getManagerForClass($class);

        if (!$em instanceof EntityManagerInterface) {
            throw new \UnexpectedValueException(sprintf('No entity manager defined for class "%s".', $class));
        }

        return $em;
    }
```
