### ISSUE TITLE
Is this bundle compatible with the new sonata.exporter.exporter service ?

### ISSUE THREAD

**Issue by acrozes** [sonata-project/SonataDoctrineORMAdminBundle#671]
After UPGRADE FROM 3.13 to 3.14 the exporter function does not work any more in my project ...

**Comment by greg0ire** [comment]
This is probably my fault. Can you tell us more?

**Comment by acrozes** [comment]
I try to fix the BC exporter doing that:

composer extract:

> "sonata-project/admin-bundle" : "~3.2",
> "sonata-project/doctrine-mongodb-admin-bundle": "dev-master",
> "sonata-project/exporter" : "^1.7",

bundle extract:
>             new Sonata\CoreBundle\SonataCoreBundle(),
>             new Sonata\BlockBundle\SonataBlockBundle(),
>             new Knp\Bundle\MenuBundle\KnpMenuBundle(),
>             new Sonata\DoctrineMongoDBAdminBundle\SonataDoctrineMongoDBAdminBundle(),
>             new Exporter\Bridge\Symfony\Bundle\SonataExporterBundle(),
>             new Sonata\AdminBundle\SonataAdminBundle(),

added in the config (I don't know if it is optionnal - I try with and without):
```
sonata_exporter:
    exporter:
        default_writers:
            - csv
            - json
            - xls 
            - xml
```
